### ISSUE TITLE
Error after adding the package @types/redux-state-sync

### ISSUE THREAD

**Issue by malininss** [aohua/redux-state-sync#143]
I use the lib redux-state-sync without problem - everything works fine. But when i add the packages  with types @types/redux-state-sync i get an error:

`
index.js:41662 Uncaught TypeError: _broadcastChannel.BroadcastChannel is not a constructor
    at createStateSyncMiddleware (index.js:41662:19)
    at configureStore (index.js:44006:232)
`

What could be the reason for this error?

**Comment by aohua** [comment]
Hi,

you may want to check the type definition in definitely-typed repo to check
the issue. Don't have time to maintain the library now.
